language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "git clone git://github.com/thongdong7/subfind-provider.git --branch=2.0-dev"
  - "git clone git://github.com/thongdong7/subfind-provider-subscene.git --branch=2.0-dev"
  - "export PYTHON_PATH=`pwd`:`pwd`/subfind-provider:`pwd`/subfind-provider-subscene"
#  - python setup.py install
# command to run tests
script:
  - nosetests
  # Test cli
#  - subfind -h
