language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  # Could not run on pypy due to lxml
#  - "pypy"
# command to install dependencies
before_install:
  - pip install lxml Distance==0.1.3
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install importlib; fi

# command to run tests
script:
  - nosetests