language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - nosetests
  # Test cli.py
  - python subfind/cli.py
  - python subfind/cli.py -h
#  - python subfind/cli.py -d tests/data
  # Install and ensure the command line could run
  - python setup.py install
  - subfind
