components:
  - name: Switch
    css:
      - styles/switch.scss

params:
  reactVersion: &reactVersion "15.0.1"
extraComponents:
  - name: react
    version: *reactVersion
  - name: react-dom
    version: *reactVersion
  - name: react-addons-update
    version: *reactVersion
  - name: react-router
    version: "2.0.1"
  - name: react-typeahead
    version: "1.1.6"
  - name: jquery
    version: "^2.2.3"
  - name: ionicons
    version: "3.0.0-alpha.3"
  - name: font-awesome
    version: "4.5.0"
  - name: admin-lte
    version: "2.3.2"
    css:
      - admin-lte/bootstrap/css/bootstrap.min.css
      - font-awesome/css/font-awesome.min.css
      - ionicons/dist/css/ionicons.min.css
      - admin-lte/dist/css/AdminLTE.min.css
      - admin-lte/dist/css/skins/skin-blue.min.css
  - name: patternfly
    version: "^3.3.3"
    css:
      - patternfly/dist/css/patternfly.min.css
  - name: toastr
    css:
      - toastr/toastr.scss
    webpackImport: true
    version: "^2.1.2"
template:
#  - path: client/main.js

